### ISSUE TITLE
Spawners are inconsistent

### ISSUE THREAD

**Issue by KekkyShmekky** [Guthen/VKXToolsEntitySpawner#4]
Even though the delay is set to 1 second and I am inside the radius for that long, the entities don't spawn. I am trying to do this with Simfphys vehicles.

**Comment by Guthen** [comment]
Hey, might be an entity which prevent your vehicles from spawning, can you set the convar `vkx_entspawner_debug 1` in the server's console, try again and send me the console output?

**Comment by KekkyShmekky** [comment]
VKX Entity Spawner ─ Debug: "Player [1][|KB| >KEKSQUAD]" is blocking "Entity [1684][gmod_sent_vehicle_fphysics_base]" from spawning
VKX Entity Spawner ─ Debug: "Player [1][|KB| >KEKSQUAD]" is blocking "Entity [1684][gmod_sent_vehicle_fphysics_base]" from spawning
[guthlevelsystem] - Data has been saved on "|KB| >KEKSQUAD"
VKX Entity Spawner ─ Debug: "Player [1][|KB| >KEKSQUAD]" is blocking "Entity [1710][gmod_sent_vehicle_fphysics_base]" from spawning
VKX Entity Spawner ─ Debug: "Player [1][|KB| >KEKSQUAD]" is blocking "Entity [1710][gmod_sent_vehicle_fphysics_base]" from spawning
VKX Entity Spawner ─ Debug: "Entity [34][dlib_predictednw0]" is blocking "Entity [1710][gmod_sent_vehicle_fphysics_base]" from spawning
VKX Entity Spawner ─ Debug: "Player [1][|KB| >KEKSQUAD]" is blocking "Entity [34][gmod_sent_vehicle_fphysics_base]" from spawning
VKX Entity Spawner ─ Debug: "Player [1][|KB| >KEKSQUAD]" is blocking "Entity [34][gmod_sent_vehicle_fphysics_base]" from spawning
VKX Entity Spawner ─ Debug: "Player [1][|KB| >KEKSQUAD]" is blocking "Entity [34][gmod_sent_vehicle_fphysics_base]" from spawning
VKX Entity Spawner ─ Debug: "Entity [1665][gmod_sent_vehicle_fphysics_base]" is blocking "Entity [34][gmod_sent_vehicle_fphysics_base]" from spawning
VKX Entity Spawner ─ Debug: "Player [1][|KB| >KEKSQUAD]" is blocking "Entity [34][gmod_sent_vehicle_fphysics_base]" from spawning
VKX Entity Spawner ─ Debug: "Entity [1665][gmod_sent_vehicle_fphysics_base]" is blocking "Entity [34][gmod_sent_vehicle_fphysics_base]" from spawning
VKX Entity Spawner ─ Debug: "Entity [366][predicted_viewmodel]" is blocking "Entity [34][gmod_sent_vehicle_fphysics_base]" from spawning
VKX Entity Spawner ─ Debug: "Player [1][|KB| >KEKSQUAD]" is blocking "Entity [34][gmod_sent_vehicle_fphysics_base]" from spawning

**Comment by KekkyShmekky** [comment]
Perhaps a command or something along those lines to make stuff such as "predicted_viewmodel" ignored by the spheres?

**Comment by Guthen** [comment]
Looks like yourself is blocking most of the vehicles, try not to be that close. If you want to blacklist an entity class by yourself, you can go to the file `lua\autorun\vkx_entspawner.lua` and add the entity class in the blacklist table (line 5)

Actually, the spheres are just visual but are not used to check if an entity can spawn correctly, I use the model bounds for that. So entities should not be too close depending on the model.

I just made a commit (bc7a20f38f9f131aa9eb3dd9a5f749371f9a111b) to blacklist `physgun_beam` and `predicted_viewmodel`

Tell me if there is anything new

**Comment by Guthen** [comment]
I believe this is fixed
